GET http://localhost:3001/api/User

###

POST http://localhost:3001/api/User
Content-type: application/json

{
    "name": "Augustin",
    "first_name": "Augustin",
    "phone_number": "Augustin",
    "mail": "Augustin",
    "password": "Augustin"
}

###

POST http://localhost:3001/auth/login
Content-type: application/json

{
    "email": "a",
    "password": "a"
}

###

GET http://localhost:3001/api/servers


###

POST http://localhost:3001/api/servers
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUiLCJtYWlsIjoiQXVndXN0aW4iLCJuYW1lIjoiQXVndXN0aW4iLCJpYXQiOjE3NzAzMTY3ODIsImV4cCI6MTc3MDMyMDM4Mn0.2zGuvMsHEaWb0Z_0lrHN6efu8luz3e1D4CkUelWAYQI

{
    "name": "Augustin3"
}

###

GET http://localhost:3001/api/servers/1/inviteCode
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUiLCJtYWlsIjoiQXVndXN0aW4iLCJuYW1lIjoiQXVndXN0aW4iLCJpYXQiOjE3NzAzMTY3ODIsImV4cCI6MTc3MDMyMDM4Mn0.2zGuvMsHEaWb0Z_0lrHN6efu8luz3e1D4CkUelWAYQI

###

GET http://localhost:3001/api/servers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJtYWlsIjoiYSIsIm5hbWUiOiJhIiwiaWF0IjoxNzcwMzM1ODU4LCJleHAiOjE3NzAzNTc0NTh9.Ql-mouuATIynyreUctjV3cAkHw95zGgn352_E2KbbKM

###

POST http://localhost:3001/api/servers/join
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUiLCJtYWlsIjoiQXVndXN0aW4iLCJuYW1lIjoiQXVndXN0aW4iLCJpYXQiOjE3NzAzMTY3ODIsImV4cCI6MTc3MDMyMDM4Mn0.2zGuvMsHEaWb0Z_0lrHN6efu8luz3e1D4CkUelWAYQI

{
  "inviteCode": "86a89589f0a3048f8ab5d2288bafcff8"
}

###

GET http://localhost:3001/api/servers/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJtYWlsIjoiQXVndXN0aW4iLCJuYW1lIjoiQXVndXN0aW4iLCJpYXQiOjE3NzAzMDU3MjYsImV4cCI6MTc3MDMwOTMyNn0.WloPoau6Y_BoicSkeFCxhoP60T4Kgv8HaOxDVmUYOB8


###
DELETE http://localhost:3001/api/servers/1/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJtYWlsIjoiQXVndXN0aW4iLCJuYW1lIjoiQXVndXN0aW4iLCJpYXQiOjE3NzAzMDUyMjMsImV4cCI6MTc3MDMwODgyM30.F3_fsesZ14iznH2kesW6KVatsaEX6AVRDwaCw45tzCI

###
POST http://localhost:3001/api/servers/1/channels
Content-type: application/json

{
    "name": "Augustin3"
}

###
GET http://localhost:3001/api/servers/2/channels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJtYWlsIjoiYSIsIm5hbWUiOiJhIiwiaWF0IjoxNzcwMzM1ODU4LCJleHAiOjE3NzAzNTc0NTh9.Ql-mouuATIynyreUctjV3cAkHw95zGgn352_E2KbbKM


###
GET http://localhost:3001/api/servers/channel/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJtYWlsIjoiQXVndXN0aW4iLCJuYW1lIjoiQXVndXN0aW4iLCJpYXQiOjE3NzAzMDUyMjMsImV4cCI6MTc3MDMwODgyM30.F3_fsesZ14iznH2kesW6KVatsaEX6AVRDwaCw45tzCI
